### ISSUE TITLE
Make "Could not get context..." error not "blinking"?

### ISSUE THREAD

**Issue by apawlik** [stencila/desktop#46]
When typing code in a cell that has a selected execution context currently unavailable the error message keeps "blinking" - that is, it is not visible when one is typing but it shows up when a user stops typing. Probably would be better for consistency to have it on all the time (it would also keep reminding the user which context they set they cell in).

Useful but not critical and possibly related to https://github.com/stencila/stencila/issues/641
![context_error_blink](https://user-images.githubusercontent.com/2358535/39566621-535887e2-4f10-11e8-960c-c2308f318dac.gif)

**Comment by oliver----** [comment]
Ok.
At the moment, we hide the error from the user to not annoy them while typing, where usually errors occur.
Now this is technically a bit 'nasty', because the context error happens as part of the evaluation (particularly `context.analyseCode()`), at the moment.
@nokome maybe we should make the missing context check more of a  pre-condition?

**Comment by apawlik** [comment]
Yes, I thought this is all "bundled up". As said, this is an enhancement and may be resolved later on

**Comment by nokome** [comment]
I agree with @oliver---- that unavailable execution context should be treated differently to run time errors. I'm not sure if we should treat this as a 'pre-condition' (you mean like "yellow" cells?), or perhaps instead handle the display of different types of errors differently e.g. `context-error`, `syntax-error`, `runtime-error` etc (with `context-error` always shown).

Generally, we need to have better UX for errors. For example, instead of `Could not get execution context for sql`, it would be great to have a link next to the message to a section of the help describing how to get an SQL context. Same for other types of errors, e.g. `Unresolved input` should link to a resource on understanding the dependency graph/engine. Turn errors into learning opportunities.

Also, I've been finding myself wanting to know where errors came from: for the execution engine (e.g. `Unresolved input`) or execution contexts. I think that could help the user reason about what is going on where.

**Comment by nokome** [comment]
Should this be the focus of a dedicated iteration sometime? Probably deserves a card in the roadmap and a new issue in stencila/stencila (and close this one, but refer to it)?

**Comment by oliver----** [comment]
Yep. Let's do a dedicated UX iteration for errors.
