### ISSUE TITLE
Need to specify python2.7 and install electron with every installation from the source

### ISSUE THREAD

**Issue by arinbasu** [stencila/desktop#55]
Hi All,
Each time I want to install Stencila desktop from the source, in Mac (10.13.4, Mac OS High Sierra), I need to issue:

```
npm install --python=python2.7
```
Otherwise the installation fails at integer@1.0.3 
The other thing is, with post install, I need to do something like:

```
npm install electron
```
otherwise the postinstallation does not work. Can you kindly fix these issues?

**Comment by nokome** [comment]
Thanks for the feedback @arinbasu. 

The first issue re specifying the Python version is due to a dependency that we are using to provide a built-in SQL execution context (`better-sqlite3`). It also seems to be causing issues with Windows builds. One option is to drop that dependency to make it easier for people like you who want to build from source. But that would reduce functionality and/or require an extra install step for users who a downloading the pre-built installers we provide. So I think it is worth perservering along the current route and improving installation instructions and build scripts.

I will create so Travis (Linux & Mac) and Appveyor (Windows) config files that do automatic builds of `stencila/desktop` and `stencila/node` (which is where the `better-sqlite3` dependency enters).

**Comment by apawlik** [comment]
@arinbasu just a short note to avoid confusion. Even though whilst installing `stencila` you need to use Python 2.7, you can still run Python 3 code in Stencila, you need to explicitly register the package with Python 3 
python3 -m stencila register
